/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PiggyBankFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "createPiggyBank"
      | "getPiggyBankBalance"
      | "getUserAccountCount"
      | "getUserSavings"
      | "userAccountCount"
      | "userSavings"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createPiggyBank",
    values: [BigNumberish, boolean, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPiggyBankBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserAccountCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSavings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userAccountCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userSavings",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createPiggyBank",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPiggyBankBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserAccountCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserSavings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userAccountCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userSavings",
    data: BytesLike
  ): Result;
}

export interface PiggyBankFactory extends BaseContract {
  connect(runner?: ContractRunner | null): PiggyBankFactory;
  waitForDeployment(): Promise<this>;

  interface: PiggyBankFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  createPiggyBank: TypedContractMethod<
    [lockPeriod: BigNumberish, isETH: boolean, tokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getPiggyBankBalance: TypedContractMethod<
    [piggyBankAddress: AddressLike],
    [bigint],
    "view"
  >;

  getUserAccountCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getUserSavings: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  userAccountCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  userSavings: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createPiggyBank"
  ): TypedContractMethod<
    [lockPeriod: BigNumberish, isETH: boolean, tokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPiggyBankBalance"
  ): TypedContractMethod<[piggyBankAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserAccountCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserSavings"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "userAccountCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userSavings"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  filters: {};
}
