/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as piggySol from "./Piggy.sol";
export type { piggySol };
import type * as piggyFactorySol from "./PiggyFactory.sol";
export type { piggyFactorySol };
import type * as interfaces from "./interfaces";
export type { interfaces };
