/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20Permit } from "./IERC20Permit";
export type { IUniswapV2Router } from "./IUniswapV2Router";
