/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from "./contracts";
export type { contracts };
import type * as interfaces from "./interfaces";
export type { interfaces };
export * as factories from "./factories";
export type { MyToken } from "./contracts/Token.sol/MyToken";
export { MyToken__factory } from "./factories/contracts/Token.sol/MyToken__factory";
export type { IERC20 } from "./interfaces/IERC20";
export { IERC20__factory } from "./factories/interfaces/IERC20__factory";
