/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EmployeeManagement__factory } from "./EmployeeManagement__factory";
export { IEmployeePayment__factory } from "./IEmployeePayment__factory";
