/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IPay, IPayInterface } from "../IPay";

const _abi = [
  {
    inputs: [
      {
        internalType: "address payable",
        name: "_to",
        type: "address",
      },
    ],
    name: "paySalary",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IPay__factory {
  static readonly abi = _abi;
  static createInterface(): IPayInterface {
    return new Interface(_abi) as IPayInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPay {
    return new Contract(address, _abi, runner) as unknown as IPay;
  }
}
