/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EmployeeManagement } from "./EmployeeManagement";
export type { IEmployeePayment } from "./IEmployeePayment";
export * as factories from "./factories";
export { EmployeeManagement__factory } from "./factories/EmployeeManagement__factory";
export { IEmployeePayment__factory } from "./factories/IEmployeePayment__factory";
