/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as piggySol from "./Piggy.sol";
export * as piggyFactorySol from "./PiggyFactory.sol";
export * as interfaces from "./interfaces";
