/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ownTodoSol from "./OwnTodo.sol";
export type { ownTodoSol };
import type * as studentMgtSol from "./StudentMGT.sol";
export type { studentMgtSol };
export * as factories from "./factories";
export type { TodoList } from "./OwnTodo.sol/TodoList";
export { TodoList__factory } from "./factories/OwnTodo.sol/TodoList__factory";
export type { StudentManagementSystem } from "./StudentMGT.sol/StudentManagementSystem";
export { StudentManagementSystem__factory } from "./factories/StudentMGT.sol/StudentManagementSystem__factory";
